<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function find_all(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sort_column(elem) {
    toggle_sort_states(elem);
    var colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    var key;
    if (elem.classList.contains('numeric')) {
        key = key_num;
    } else if (elem.classList.contains('result')) {
        key = key_result;
    } else {
        key = key_alpha;
    }
    sort_table(elem, key(colIndex));
}

function show_all_extras() {
    find_all('.col-result').forEach(show_extras);
}

function hide_all_extras() {
    find_all('.col-result').forEach(hide_extras);
}

function show_extras(colresult_elem) {
    var extras = colresult_elem.parentNode.nextElementSibling;
    var expandcollapse = colresult_elem.firstElementChild;
    extras.classList.remove("collapsed");
    expandcollapse.classList.remove("expander");
    expandcollapse.classList.add("collapser");
}

function hide_extras(colresult_elem) {
    var extras = colresult_elem.parentNode.nextElementSibling;
    var expandcollapse = colresult_elem.firstElementChild;
    extras.classList.add("collapsed");
    expandcollapse.classList.remove("collapser");
    expandcollapse.classList.add("expander");
}

function show_filters() {
    var filter_items = document.getElementsByClassName('filter');
    for (var i = 0; i < filter_items.length; i++)
        filter_items[i].hidden = false;
}

function add_collapse() {
    // Add links for show/hide all
    var resulttable = find('table#results-table');
    var showhideall = document.createElement("p");
    showhideall.innerHTML = '<a href="javascript:show_all_extras()">Show all details</a> / ' +
                            '<a href="javascript:hide_all_extras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    find_all('.col-result').forEach(function(elem) {
        var collapsed = get_query_parameter('collapsed') || 'Passed';
        var extras = elem.parentNode.nextElementSibling;
        var expandcollapse = document.createElement("span");
        if (extras.classList.contains("collapsed")) {
            expandcollapse.classList.add("expander")
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add("collapsed");
            expandcollapse.classList.add("expander");
        } else {
            expandcollapse.classList.add("collapser");
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener("click", function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains("collapsed")) {
                show_extras(event.currentTarget);
            } else {
                hide_extras(event.currentTarget);
            }
        });
    })
}

function get_query_parameter(name) {
    var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () {
    reset_sort_headers();

    add_collapse();

    show_filters();

    sort_column(find('.initial-sort'));

    find_all('.sortable').forEach(function(elem) {
        elem.addEventListener("click",
                              function(event) {
                                  sort_column(elem);
                              }, false)
    });

};

function sort_table(clicked, key_func) {
    var rows = find_all('.results-table-row');
    var reversed = !clicked.classList.contains('asc');
    var sorted_rows = sort(rows, key_func, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    var thead = document.getElementById("results-table-head");
    document.getElementById('results-table').remove();
    var parent = document.createElement("table");
    parent.id = "results-table";
    parent.appendChild(thead);
    sorted_rows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName("BODY")[0].appendChild(parent);
}

function sort(items, key_func, reversed) {
    var sort_array = items.map(function(item, i) {
        return [key_func(item), i];
    });

    sort_array.sort(function(a, b) {
        var key_a = a[0];
        var key_b = b[0];

        if (key_a == key_b) return 0;

        if (reversed) {
            return (key_a < key_b ? 1 : -1);
        } else {
            return (key_a > key_b ? 1 : -1);
        }
    });

    return sort_array.map(function(item) {
        var index = item[1];
        return items[index];
    });
}

function key_alpha(col_index) {
    return function(elem) {
        return elem.childNodes[1].childNodes[col_index].firstChild.data.toLowerCase();
    };
}

function key_num(col_index) {
    return function(elem) {
        return parseFloat(elem.childNodes[1].childNodes[col_index].firstChild.data);
    };
}

function key_result(col_index) {
    return function(elem) {
        var strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
                       'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[col_index].firstChild.data);
    };
}

function reset_sort_headers() {
    find_all('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    find_all('.sortable').forEach(function(elem) {
        var icon = document.createElement("div");
        icon.className = "sort-icon";
        icon.textContent = "vvv";
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove("desc", "active");
        elem.classList.add("asc", "inactive");
    });
}

function toggle_sort_states(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        reset_sort_headers();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function is_all_rows_hidden(value) {
  return value.hidden == false;
}

function filter_table(elem) {
    var outcome_att = "data-test-result";
    var outcome = elem.getAttribute(outcome_att);
    class_outcome = outcome + " results-table-row";
    var outcome_rows = document.getElementsByClassName(class_outcome);

    for(var i = 0; i < outcome_rows.length; i++){
        outcome_rows[i].hidden = !elem.checked;
    }

    var rows = find_all('.results-table-row').filter(is_all_rows_hidden);
    var all_rows_hidden = rows.length == 0 ? true : false;
    var not_found_message = document.getElementById("not-found-message");
    not_found_message.hidden = !all_rows_hidden;
}
</script>
    <h1>report.html</h1>
    <p>Report generated on 10-Apr-2020 at 01:46:37 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v2.1.1</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "0.13.1", "py": "1.8.1", "pytest": "5.4.1"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-10-10.0.18362-SP0</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"html": "2.1.1", "metadata": "1.8.0"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.8.2</td></tr></table>
    <h2>Summary</h2>
    <p>5 tests ran in 29.58 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="passed">5 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" disabled="true" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="failed">0 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filter_table(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable numeric" col="duration">Duration</th>
          <th>Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_HomePage.py::TestHomePage::test_formSubmit[getData0]</td>
          <td class="col-duration">0.79</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_HomePage.py::TestHomePage::test_formSubmit[getData1]</td>
          <td class="col-duration">0.70</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_HomePage.py::TestHomePage::test_getLogger</td>
          <td class="col-duration">0.24</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_e2e.py::TestOne::test_e2e</td>
          <td class="col-duration">7.30</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stderr call------------------------------ <br/>--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 74, in format
    return super().format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 310, in emit
    logging.StreamHandler.emit(self, record)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 74, in format
    return super().format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 310, in emit
    logging.StreamHandler.emit(self, record)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 74, in format
    return super().format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 310, in emit
    logging.StreamHandler.emit(self, record)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 74, in format
    return super().format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 27, in test_e2e
    log.info(&quot;card Text : &quot;, pname)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 310, in emit
    logging.StreamHandler.emit(self, record)
Message: &#x27;card Text : &#x27;
Arguments: (&#x27;iphone X&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 43, in test_e2e
    log.info(&quot;Text received from application is :&quot;,txt)
Message: &#x27;Text received from application is :&#x27;
Arguments: (&#x27;×\nSuccess! Thank you! Your order will be delivered in next few weeks :-).&#x27;,)
--- Logging error ---
Traceback (most recent call last):
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1081, in emit
    msg = self.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 925, in format
    return fmt.format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 74, in format
    return super().format(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 664, in format
    record.message = record.getMessage()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;C:\Users\acer\AppData\Local\Programs\Python\Python38-32\Scripts\py.test.exe\__main__.py&quot;, line 9, in &lt;module&gt;
    sys.exit(main())
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py&quot;, line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 100, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 216, in call_runtest_hook
    return CallInfo.from_call(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 244, in from_call
    result = func()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 217, in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\runner.py&quot;, line 135, in pytest_runtest_call
    item.runtest()
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 1479, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\python.py&quot;, line 184, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File &quot;C:\Users\acer\PycharmProjects\PythonFramework\Tests\test_e2e.py&quot;, line 43, in test_e2e
    log.info(&quot;Text received from application is :&quot;,txt)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1577, in _log
    self.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1587, in handle
    self.callHandlers(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 1649, in callHandlers
    hdlr.handle(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\logging\__init__.py&quot;, line 950, in handle
    self.emit(record)
  File &quot;c:\users\acer\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\logging.py&quot;, line 310, in emit
    logging.StreamHandler.emit(self, record)
Message: &#x27;Text received from application is :&#x27;
Arguments: (&#x27;×\nSuccess! Thank you! Your order will be delivered in next few weeks :-).&#x27;,)
<br/> -------------------------------Captured log call-------------------------------- <br/>[32mINFO    [0m test_e2e:test_e2e.py:20 getting all the cart items
[32mINFO    [0m test_e2e:test_e2e.py:34 Entering country name as India<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_e2e.py::TestOne::test_getLogger</td>
          <td class="col-duration">0.02</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="empty log">No log output captured.</div></td></tr></tbody></table></body></html>